name: 'polymer_dart_example'
version: 0.0.1
description: A web app built using polymer.dart.
#author: Your Name <email@example.com>

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  analyzer: 0.26.1+14
  browser: ^0.10.0
  polymer: ^1.0.0-rc.2
  reflectable: ^0.3.1
  web_components: ^0.12.0

transformers:
- web_components:
    entry_points: web/index.html
- reflectable:
    entry_points: web/index.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
